import { Command } from 'commander';
import { existsSync, readFileSync, readdirSync, statSync } from 'fs';
import { join } from 'path';
import { atomicWriteSync } from '../utils/atomic.js';

const NAME_RE = /^[A-Za-z0-9_-]+$/;

export const goalsCommand = new Command('goals')
  .description('Manage goals.json and auto-generate GOALS.md for agents');

// ---------------------------------------------------------------------------
// Shared helpers (reused by generate-md + cascade)
// ---------------------------------------------------------------------------

export interface GoalsData {
  focus?: string;
  goals?: Array<string | { title: string }>;
  bottleneck?: string;
  updated_at?: string;
  updated_by?: string;
}

/** Render GOALS.md text from a parsed goals.json object. */
export function renderGoalsMd(agent: string, org: string, data: GoalsData): string {
  const goals = Array.isArray(data.goals) ? data.goals : [];
  const focus = typeof data.focus === 'string' ? data.focus : '';
  const bottleneck = typeof data.bottleneck === 'string' ? data.bottleneck : '';
  const updatedAt = typeof data.updated_at === 'string' ? data.updated_at : new Date().toISOString();
  const updatedBy = typeof data.updated_by === 'string' ? data.updated_by : '';

  const lines: string[] = [
    '# Goals',
    '',
    '> Auto-generated from goals.json. Do not edit this file directly.',
    `> To regenerate: \`cortextos goals generate-md --agent ${agent} --org ${org}\``,
    '',
    '## Focus',
    focus || '(not set — check with your orchestrator)',
    '',
    '## Goals',
  ];

  if (goals.length === 0) {
    lines.push('(none set — message your orchestrator to request today\'s goals)');
  } else {
    goals.forEach((g, i) => {
      const title = typeof g === 'string' ? g : (g as { title: string }).title;
      lines.push(`${i + 1}. ${title}`);
    });
  }

  lines.push(
    '',
    '## Bottleneck',
    bottleneck || '(none)',
    '',
    '## Updated',
    updatedBy ? `${updatedAt} (by ${updatedBy})` : updatedAt,
    '',
  );

  return lines.join('\n');
}

/** Read an agent's goals.json + atomically (re)write its GOALS.md. Returns false if goals.json is missing/corrupt. */
export function regenGoalsMd(frameworkRoot: string, org: string, agent: string): boolean {
  const agentDir = join(frameworkRoot, 'orgs', org, 'agents', agent);
  const goalsJsonPath = join(agentDir, 'goals.json');
  if (!existsSync(goalsJsonPath)) return false;
  let data: GoalsData;
  try {
    data = JSON.parse(readFileSync(goalsJsonPath, 'utf-8')) as GoalsData;
  } catch {
    return false;
  }
  atomicWriteSync(join(agentDir, 'GOALS.md'), renderGoalsMd(agent, org, data));
  return true;
}

/** Roster = subdirectories of orgs/<org>/agents/ that contain an IDENTITY.md (real agents). */
export function loadRoster(frameworkRoot: string, org: string): string[] {
  const agentsDir = join(frameworkRoot, 'orgs', org, 'agents');
  if (!existsSync(agentsDir)) return [];
  return readdirSync(agentsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(agentsDir, d.name, 'IDENTITY.md')))
    .map((d) => d.name)
    .sort();
}

/** UTC date (YYYY-MM-DD) of an ISO timestamp, or null if unparseable. */
function utcDate(iso: unknown): string | null {
  if (typeof iso !== 'string') return null;
  const t = Date.parse(iso);
  if (Number.isNaN(t)) return null;
  return new Date(t).toISOString().slice(0, 10);
}

// ---------------------------------------------------------------------------
// cortextos goals generate-md --agent <name> --org <org>
// ---------------------------------------------------------------------------
goalsCommand
  .command('generate-md')
  .description('Regenerate GOALS.md from goals.json for an agent')
  .requiredOption('--agent <name>', 'Agent name')
  .requiredOption('--org <org>', 'Org name')
  .action((options: { agent: string; org: string }) => {
    const frameworkRoot = process.env.CTX_FRAMEWORK_ROOT || process.cwd();
    if (!NAME_RE.test(options.agent) || !NAME_RE.test(options.org)) {
      process.stderr.write('Error: agent and org must be alphanumeric/dash/underscore only\n');
      process.exit(1);
    }
    const goalsJsonPath = join(frameworkRoot, 'orgs', options.org, 'agents', options.agent, 'goals.json');
    if (!existsSync(goalsJsonPath)) {
      process.stderr.write(`goals.json not found at ${goalsJsonPath}\n`);
      process.exit(1);
    }
    if (!regenGoalsMd(frameworkRoot, options.org, options.agent)) {
      process.stderr.write(`Failed to parse goals.json for ${options.agent}\n`);
      process.exit(1);
    }
    console.log(`Generated GOALS.md for ${options.agent}`);
  });

// ---------------------------------------------------------------------------
// cortextos goals cascade --input <staging.json> --org <org> [--dry-run]
//
// Atomic, verified daily goal cascade. Writes org daily_focus + every staged
// agent's goals.json, regenerates each GOALS.md, then VERIFIES the WHOLE roster
// (not just staged agents) is fresh-today — failing loud if any agent is stale.
// This makes "all-N-fresh" an enforced invariant: omit an agent → verify fails.
// ---------------------------------------------------------------------------

interface StagingAgent { focus?: string; goals?: string[]; bottleneck?: string; }
interface Staging { daily_focus?: string; agents?: Record<string, StagingAgent>; }

export interface CascadeResult { exitCode: number; out: string[]; err: string[]; }

/**
 * Core of `goals cascade` — pure-ish (no process.exit / no console). Returns an
 * exit code + stdout/stderr lines so it is unit-testable. The action wrapper
 * does the printing + process.exit.
 */
export function runCascade(
  frameworkRoot: string,
  options: { input: string; org: string; dryRun?: boolean },
): CascadeResult {
  const out: string[] = [];
  const err: string[] = [];
  const runStartMs = Date.now();
  const nowIso = new Date(runStartMs).toISOString();
  const todayUtc = nowIso.slice(0, 10);
  const fail = (msg: string): CascadeResult => { err.push(`Error: ${msg}`); return { exitCode: 1, out, err }; };

  if (!NAME_RE.test(options.org)) return fail('org must be alphanumeric/dash/underscore only');
  const orgDir = join(frameworkRoot, 'orgs', options.org);
  if (!existsSync(orgDir)) return fail(`org not found: ${orgDir}`);

  // --- Load + parse staging ---
  if (!existsSync(options.input)) return fail(`input not found: ${options.input}`);
  let staging: Staging;
  try {
    staging = JSON.parse(readFileSync(options.input, 'utf-8')) as Staging;
  } catch {
    return fail(`failed to parse staging JSON: ${options.input}`);
  }
  if (typeof staging.daily_focus !== 'string' || !staging.daily_focus.trim()) {
    return fail('staging.daily_focus is required and must be a non-empty string');
  }
  if (!staging.agents || typeof staging.agents !== 'object' || Array.isArray(staging.agents)) {
    return fail('staging.agents is required and must be an object');
  }

  // --- Validate against roster (fail loud, ZERO writes) ---
  const roster = loadRoster(frameworkRoot, options.org);
  if (roster.length === 0) return fail(`no roster agents found under orgs/${options.org}/agents/`);
  const staged = Object.entries(staging.agents);
  if (staged.length === 0) return fail('staging.agents is empty');
  for (const [name, a] of staged) {
    if (!roster.includes(name)) return fail(`unknown agent in staging: '${name}' (roster: ${roster.join(', ')})`);
    if (typeof a.focus !== 'string' || !a.focus.trim()) return fail(`agent '${name}': non-empty 'focus' required`);
    const goals = a.goals;
    if (!Array.isArray(goals) || goals.length === 0) return fail(`agent '${name}': non-empty 'goals' array required`);
    if ((goals as unknown[]).some((g) => typeof g !== 'string' || !(g as string).trim())) return fail(`agent '${name}': all goals must be non-empty strings`);
  }

  // --- Dry run: print the plan, make NO writes ---
  if (options.dryRun) {
    out.push(`[dry-run] org ${options.org} — daily_focus: "${staging.daily_focus}"`);
    out.push(`[dry-run] would write ${staged.length} agent goals.json + regen GOALS.md:`);
    for (const [name, a] of staged) out.push(`  - ${name}: ${(a.goals as string[]).length} goals, focus="${a.focus}"`);
    const omitted = roster.filter((r) => !staging.agents![r]);
    if (omitted.length) out.push(`[dry-run] WARNING: roster agents NOT in staging (would FAIL verify): ${omitted.join(', ')}`);
    out.push('[dry-run] no files written.');
    return { exitCode: 0, out, err };
  }

  // --- Apply (atomic) ---
  // 1) org focus — merge into existing org goals.json, preserving other keys.
  const orgGoalsPath = join(orgDir, 'goals.json');
  let orgData: Record<string, unknown> = {};
  if (existsSync(orgGoalsPath)) {
    try { orgData = JSON.parse(readFileSync(orgGoalsPath, 'utf-8')); } catch { orgData = {}; }
  }
  orgData.daily_focus = staging.daily_focus;
  orgData.daily_focus_set_at = nowIso;
  atomicWriteSync(orgGoalsPath, JSON.stringify(orgData, null, 2));

  // 2) per staged agent — atomic goals.json + 3) regen GOALS.md
  for (const [name, a] of staged) {
    const goalsJson = {
      focus: a.focus,
      goals: a.goals,
      bottleneck: typeof a.bottleneck === 'string' ? a.bottleneck : '',
      updated_at: nowIso,
      updated_by: 'cascade',
    };
    atomicWriteSync(join(orgDir, 'agents', name, 'goals.json'), JSON.stringify(goalsJson, null, 2));
    regenGoalsMd(frameworkRoot, options.org, name);
  }

  // --- Verify the WHOLE roster + org (the critical step) ---
  const report: Array<{ name: string; ok: boolean; reason: string }> = [];

  let orgOk = false; let orgReason = 'missing';
  if (existsSync(orgGoalsPath)) {
    try {
      const od = JSON.parse(readFileSync(orgGoalsPath, 'utf-8'));
      orgOk = utcDate(od.daily_focus_set_at) === todayUtc;
      orgReason = orgOk ? 'fresh' : `daily_focus_set_at not today (${od.daily_focus_set_at ?? 'unset'})`;
    } catch { orgReason = 'corrupt'; }
  }
  report.push({ name: `org:${options.org}`, ok: orgOk, reason: orgReason });

  for (const name of roster) {
    const agentDir = join(orgDir, 'agents', name);
    const gj = join(agentDir, 'goals.json');
    const md = join(agentDir, 'GOALS.md');
    let ok = false; let reason = '';
    if (!existsSync(gj)) { reason = 'goals.json missing'; }
    else {
      try {
        const d = JSON.parse(readFileSync(gj, 'utf-8')) as GoalsData;
        const freshJson = utcDate(d.updated_at) === todayUtc;
        const freshMd = existsSync(md) && statSync(md).mtimeMs >= runStartMs;
        ok = freshJson && freshMd;
        if (!freshJson) reason = `updated_at not today (${d.updated_at ?? 'unset'})`;
        else if (!freshMd) reason = existsSync(md) ? 'GOALS.md stale (mtime < run start)' : 'GOALS.md missing';
        else reason = 'fresh';
      } catch { reason = 'goals.json corrupt'; }
    }
    report.push({ name, ok, reason });
  }

  for (const r of report) out.push(`  ${r.ok ? '✓' : '✗'} ${r.name} — ${r.reason}`);
  const stale = report.filter((r) => !r.ok);
  if (stale.length === 0) {
    out.push(`cascaded ${staged.length}/${staged.length}, verified all fresh (org + ${roster.length} roster agents)`);
    return { exitCode: 0, out, err };
  }
  err.push(`FAILED — stale: ${stale.map((s) => s.name).join(', ')}`);
  return { exitCode: 1, out, err };
}

goalsCommand
  .command('cascade')
  .description('Atomically apply + verify a daily goal cascade from a staging file')
  .requiredOption('--input <file>', 'Path to staging.json')
  .requiredOption('--org <org>', 'Org name')
  .option('--dry-run', 'Validate and print the plan; make no writes')
  .action((options: { input: string; org: string; dryRun?: boolean }) => {
    const frameworkRoot = process.env.CTX_FRAMEWORK_ROOT || process.cwd();
    const r = runCascade(frameworkRoot, options);
    for (const l of r.out) console.log(l);
    for (const l of r.err) process.stderr.write(l + '\n');
    process.exit(r.exitCode);
  });
